export type RootStackParam = {
  Login: undefined;
  SignUp: undefined;
  Rending: undefined;
  Main: undefined;
  Auth: undefined;
  KakaoLogin: undefined;
  NaverLogin: undefined;
  GoogleLogin: undefined;
  ChangePwd: undefined;
  Group: { screen: 'CreateGroup' | 'GroupCategory' | 'SearchResult' };
  CreateGroup: undefined;
  GroupCategory: undefined;
  SearchResult: undefined;
  SelectInterest: undefined;
  ConfirmSignUp: undefined;
  VerifyEmail: undefined;
  NewPassword: undefined;
  ConfirmChangePwd: undefined;
  Menu: { screen: 'MandalArtTheme' | 'GoalCalendar' | 'MenuChangePwd' | 'DeleteAccount' };
};
