export type RootStackParam = {
  Login: undefined;
  SignUp: undefined;
  Rending: undefined;
  Main: undefined;
  Auth: undefined;
  KakaoLogin: undefined;
  NaverLogin: undefined;
  GoogleLogin: undefined;
  ChangePwd: undefined;
  Group: { screen: 'CreateGroup' | 'GroupCategory' | 'SearchResult' };
  CreateGroup: undefined;
  GroupCategory: undefined;
  SearchResult: undefined;
  SelectInterest: undefined;
  ConfirmSignUp: undefined;
  VerifyEmail: undefined;
  NewPassword: undefined;
  ConfirmChangePwd: undefined;
  Menu: { screen: 'MandalArtTheme' | 'GoalCalendar' | 'MenuChangePwd' | 'DeleteAccount' };
  GoalDetail: undefined;
  GoalGroupBoard: undefined;
  GoalJoinRequst: undefined;
  Goal: { screen: 'GoalDetail' | 'GoalGroupBoard' | 'GoalJoinRequest' | 'GoalCreateMain' | 'GoalCreateSub' | 'GoalCreateDetail' | 'GoalCreateResult' | 'GoalCreateTheme' };
};
